# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Nudge' do
	pod ‘GoogleMaps’, ‘~> 2.1.0’
	pod ‘FacebookCore’
	pod ‘FacebookLogin’
	pod ‘FacebookShare’
	pod ‘Firebase/Core’
	pod ‘Firebase/Database’
	pod ‘Firebase/Messaging’
	pod ‘Kingfisher’
end

